all:
	pdflatex Rapport.tex
	pdflatex Rapport.tex
	rm -f *.aux
	rm -f *.cb
	rm -f *.cb2
	rm -f *.log
	rm -f *.out
	rm -f *.toc
	rm -f *~
	rm -f *.backup

clean:
	rm -f *.pdf
	rm -f *.aux
	rm -f *.cb
	rm -f *.cb2
	rm -f *.log
	rm -f *.out
	rm -f *.toc
	rm -f *~
	rm -f *.backup